/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "bam_types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(bam_types_AuthProof, bam_types_AuthProof, 2)


PB_BIND(bam_types_BuilderHeartBeat, bam_types_BuilderHeartBeat, AUTO)


PB_BIND(bam_types_ValidatorHeartBeat, bam_types_ValidatorHeartBeat, AUTO)


PB_BIND(bam_types_Ping, bam_types_Ping, AUTO)


PB_BIND(bam_types_Pong, bam_types_Pong, AUTO)


PB_BIND(bam_types_Socket, bam_types_Socket, AUTO)


PB_BIND(bam_types_LeaderState, bam_types_LeaderState, AUTO)


PB_BIND(bam_types_AtomicTxnBatch, bam_types_AtomicTxnBatch, AUTO)


PB_BIND(bam_types_MultipleAtomicTxnBatch, bam_types_MultipleAtomicTxnBatch, AUTO)


PB_BIND(bam_types_AtomicTxnBatchResult, bam_types_AtomicTxnBatchResult, 2)


PB_BIND(bam_types_MultipleAtomicTxnBatchResult, bam_types_MultipleAtomicTxnBatchResult, AUTO)


PB_BIND(bam_types_Packet, bam_types_Packet, 4)


PB_BIND(bam_types_Meta, bam_types_Meta, AUTO)


PB_BIND(bam_types_PacketFlags, bam_types_PacketFlags, AUTO)


PB_BIND(bam_types_Committed, bam_types_Committed, AUTO)


PB_BIND(bam_types_NotCommitted, bam_types_NotCommitted, 2)


PB_BIND(bam_types_DeserializationError, bam_types_DeserializationError, AUTO)


PB_BIND(bam_types_GenericInvalid, bam_types_GenericInvalid, 2)


PB_BIND(bam_types_PohTimeout, bam_types_PohTimeout, AUTO)


PB_BIND(bam_types_TransactionError, bam_types_TransactionError, AUTO)


PB_BIND(bam_types_TransactionCommittedResult, bam_types_TransactionCommittedResult, AUTO)


PB_BIND(bam_types_BlockEngineBuilderConfig, bam_types_BlockEngineBuilderConfig, AUTO)


PB_BIND(bam_types_BamConfig, bam_types_BamConfig, 2)









