/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_BAM_TYPES_BAM_TYPES_PB_H_INCLUDED
#define PB_BAM_TYPES_BAM_TYPES_PB_H_INCLUDED
#include "../../../third_party/nanopb/pb_firedancer.h"
#include "google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _bam_types_DeserializationErrorReason {
    bam_types_DeserializationErrorReason_EMPTY = 0,
    bam_types_DeserializationErrorReason_INCONSISTENT_BUNDLE = 1,
    bam_types_DeserializationErrorReason_BINCODE_ERROR = 2,
    bam_types_DeserializationErrorReason_SIGNATURE_OVERFLOWED = 3,
    bam_types_DeserializationErrorReason_SANITIZE_ERROR = 4,
    bam_types_DeserializationErrorReason_PRIORITIZATION_FAILURE = 5,
    bam_types_DeserializationErrorReason_VOTE_TRANSACTION_FAILURE = 6,
    bam_types_DeserializationErrorReason_FILTER_FAILURE = 7
} bam_types_DeserializationErrorReason;

typedef enum _bam_types_SchedulingError {
    bam_types_SchedulingError_POH_TIMEOUT = 0,
    bam_types_SchedulingError_OUTSIDE_LEADER_SLOT = 1,
    bam_types_SchedulingError_CONTAINER_FULL = 2
} bam_types_SchedulingError;

/* Source: */
typedef enum _bam_types_TransactionErrorReason {
    bam_types_TransactionErrorReason_ACCOUNT_IN_USE = 0,
    bam_types_TransactionErrorReason_ACCOUNT_LOADED_TWICE = 1,
    bam_types_TransactionErrorReason_ACCOUNT_NOT_FOUND = 2,
    bam_types_TransactionErrorReason_PROGRAM_ACCOUNT_NOT_FOUND = 3,
    bam_types_TransactionErrorReason_INSUFFICIENT_FUNDS_FOR_FEE = 4,
    bam_types_TransactionErrorReason_INVALID_ACCOUNT_FOR_FEE = 5,
    bam_types_TransactionErrorReason_ALREADY_PROCESSED = 6,
    bam_types_TransactionErrorReason_BLOCKHASH_NOT_FOUND = 7,
    bam_types_TransactionErrorReason_INSTRUCTION_ERROR = 8,
    bam_types_TransactionErrorReason_CALL_CHAIN_TOO_DEEP = 9,
    bam_types_TransactionErrorReason_MISSING_SIGNATURE_FOR_FEE = 10,
    bam_types_TransactionErrorReason_INVALID_ACCOUNT_INDEX = 11,
    bam_types_TransactionErrorReason_SIGNATURE_FAILURE = 12,
    bam_types_TransactionErrorReason_INVALID_PROGRAM_FOR_EXECUTION = 13,
    bam_types_TransactionErrorReason_SANITIZE_FAILURE = 14,
    bam_types_TransactionErrorReason_CLUSTER_MAINTENANCE = 15,
    bam_types_TransactionErrorReason_ACCOUNT_BORROW_OUTSTANDING = 16,
    bam_types_TransactionErrorReason_WOULD_EXCEED_MAX_BLOCK_COST_LIMIT = 17,
    bam_types_TransactionErrorReason_UNSUPPORTED_VERSION = 18,
    bam_types_TransactionErrorReason_INVALID_WRITABLE_ACCOUNT = 19,
    bam_types_TransactionErrorReason_WOULD_EXCEED_MAX_ACCOUNT_COST_LIMIT = 20,
    bam_types_TransactionErrorReason_WOULD_EXCEED_ACCOUNT_DATA_BLOCK_LIMIT = 21,
    bam_types_TransactionErrorReason_TOO_MANY_ACCOUNT_LOCKS = 22,
    bam_types_TransactionErrorReason_ADDRESS_LOOKUP_TABLE_NOT_FOUND = 23,
    bam_types_TransactionErrorReason_INVALID_ADDRESS_LOOKUP_TABLE_OWNER = 24,
    bam_types_TransactionErrorReason_INVALID_ADDRESS_LOOKUP_TABLE_DATA = 25,
    bam_types_TransactionErrorReason_INVALID_ADDRESS_LOOKUP_TABLE_INDEX = 26,
    bam_types_TransactionErrorReason_INVALID_RENT_PAYING_ACCOUNT = 27,
    bam_types_TransactionErrorReason_WOULD_EXCEED_MAX_VOTE_COST_LIMIT = 28,
    bam_types_TransactionErrorReason_WOULD_EXCEED_ACCOUNT_DATA_TOTAL_LIMIT = 29,
    bam_types_TransactionErrorReason_DUPLICATE_INSTRUCTION = 30,
    bam_types_TransactionErrorReason_INSUFFICIENT_FUNDS_FOR_RENT = 31,
    bam_types_TransactionErrorReason_MAX_LOADED_ACCOUNTS_DATA_SIZE_EXCEEDED = 32,
    bam_types_TransactionErrorReason_INVALID_LOADED_ACCOUNTS_DATA_SIZE_LIMIT = 33,
    bam_types_TransactionErrorReason_RESANITIZATION_NEEDED = 34,
    bam_types_TransactionErrorReason_PROGRAM_EXECUTION_TEMPORARILY_RESTRICTED = 35,
    bam_types_TransactionErrorReason_UNBALANCED_TRANSACTION = 36,
    bam_types_TransactionErrorReason_PROGRAM_CACHE_HIT_MAX_LIMIT = 37,
    bam_types_TransactionErrorReason_COMMIT_CANCELLED = 38
} bam_types_TransactionErrorReason;

/* Struct definitions */
/* The message the Validator sends to the builder to prove its identity
 based on a challenge sent by the builder */
typedef struct _bam_types_AuthProof {
    char challenge_to_sign[128];
    char validator_pubkey[64];
    char signature[128];
} bam_types_AuthProof;

/* A time-stamped heartbeat message sent by the builder to the validator */
typedef struct _bam_types_BuilderHeartBeat {
    uint64_t time_sent_microseconds; /* unix-timestamp */
} bam_types_BuilderHeartBeat;

/* A time-stamped heartbeat message sent by the validator to the builder */
typedef struct _bam_types_ValidatorHeartBeat {
    uint64_t time_sent_microseconds; /* unix-timestamp */
} bam_types_ValidatorHeartBeat;

/* A ping message sent from BAM to the validator.
 Some validators have disabled ping on their boxes, which makes it difficult to find how far 
 away they are from BAM.
 BAM shall use a randommly generated number to mitigate frontrunning Pong with determinstic id
 to make latency appear smaller than it is. */
typedef struct _bam_types_Ping {
    uint32_t id;
} bam_types_Ping;

/* A pong message sent from the validator to BAM with the same ID it received originally.
 See Ping message above for more context. */
typedef struct _bam_types_Pong {
    uint32_t id;
} bam_types_Pong;

typedef struct _bam_types_Socket {
    char ip[64];
    uint32_t port;
} bam_types_Socket;

/* Sent by the validator to the builder when it becomes the leader
 Used to inform the builder about the current leader state */
typedef struct _bam_types_LeaderState {
    uint64_t slot;
    uint32_t tick;
    uint32_t slot_cu_budget_remaining;
} bam_types_LeaderState;

/* An 'atomic transaction batch' is a bundle of transactions that must be processed together */
typedef struct _bam_types_AtomicTxnBatch {
    uint32_t seq_id; /* unique for a single leader rotation */
    uint64_t max_schedule_slot; /* slot for which this bundle is valid for execution */
    pb_callback_t packets;
} bam_types_AtomicTxnBatch;

/* A a collection of disjoint atomic transaction batches;
 meaning that batches can be evaluated independently from each other */
typedef struct _bam_types_MultipleAtomicTxnBatch {
    pb_callback_t batches;
} bam_types_MultipleAtomicTxnBatch;

/* The result of processing multiple atomic transaction batches
 Grouping is non-logical and does not imply anything
 (does not correspond with a distinct MultipleAtomicTxnBatch, for example) */
typedef struct _bam_types_MultipleAtomicTxnBatchResult {
    pb_callback_t results;
} bam_types_MultipleAtomicTxnBatchResult;

typedef struct _bam_types_PacketFlags {
    bool simple_vote_tx;
    bool revert_on_error;
} bam_types_PacketFlags;

typedef struct _bam_types_Meta {
    uint64_t size;
    bool has_flags;
    bam_types_PacketFlags flags;
} bam_types_Meta;

typedef PB_BYTES_ARRAY_T(4096) bam_types_Packet_data_t;
/* A Solana network packet */
typedef struct _bam_types_Packet {
    bam_types_Packet_data_t data;
    bool has_meta;
    bam_types_Meta meta;
} bam_types_Packet;

typedef struct _bam_types_Committed {
    pb_callback_t transaction_results;
} bam_types_Committed;

typedef struct _bam_types_DeserializationError {
    uint32_t index; /* index of the packet in the bundle */
    bam_types_DeserializationErrorReason reason; /* reason for the error */
} bam_types_DeserializationError;

typedef struct _bam_types_GenericInvalid {
    char message[256]; /* human-readable error message */
} bam_types_GenericInvalid;

typedef struct _bam_types_PohTimeout {
    char dummy_field;
} bam_types_PohTimeout;

typedef struct _bam_types_TransactionError {
    uint32_t index; /* index of the transaction in the bundle */
    bam_types_TransactionErrorReason reason; /* reason for the error */
} bam_types_TransactionError;

typedef struct _bam_types_NotCommitted {
    pb_size_t which_reason;
    union {
        bam_types_TransactionError transaction_error;
        bam_types_SchedulingError scheduling_error;
        bam_types_GenericInvalid generic_invalid;
        bam_types_DeserializationError deserialization_error;
    } reason;
} bam_types_NotCommitted;

/* The result of processing an atomic transaction batch */
typedef struct _bam_types_AtomicTxnBatchResult {
    uint32_t seq_id; /* unique for a single leader rotation (response to above Bundle message) */
    pb_size_t which_result;
    union {
        bam_types_Committed committed;
        bam_types_NotCommitted not_committed;
    } result;
} bam_types_AtomicTxnBatchResult;

typedef struct _bam_types_TransactionCommittedResult {
    uint32_t cus_consumed;
    uint64_t feepayer_balance_lamports;
    uint32_t loaded_accounts_data_size;
    bool execution_success;
} bam_types_TransactionCommittedResult;

/* Configuration for the block-engine builder */
typedef struct _bam_types_BlockEngineBuilderConfig {
    char builder_pubkey[64];
    /* commission as a percentage (0-100) */
    uint32_t builder_commission;
} bam_types_BlockEngineBuilderConfig;

/* Configuration for the BAM node */
typedef struct _bam_types_BamConfig {
    char prio_fee_recipient_pubkey[64]; /* Recipient pubkey of the priority fee commission */
    uint32_t commission_bps; /* Commission in basis points */
    bool has_tpu_sock;
    bam_types_Socket tpu_sock; /* Socket for the TPU connection */
    bool has_tpu_fwd_sock;
    bam_types_Socket tpu_fwd_sock; /* Socket for the TPU forward connection */
    pb_size_t shred_socks_count;
    bam_types_Socket shred_socks[32]; /* Socket(s) for forwarding leader and near-leader shreds */
} bam_types_BamConfig;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _bam_types_DeserializationErrorReason_MIN bam_types_DeserializationErrorReason_EMPTY
#define _bam_types_DeserializationErrorReason_MAX bam_types_DeserializationErrorReason_FILTER_FAILURE
#define _bam_types_DeserializationErrorReason_ARRAYSIZE ((bam_types_DeserializationErrorReason)(bam_types_DeserializationErrorReason_FILTER_FAILURE+1))

#define _bam_types_SchedulingError_MIN bam_types_SchedulingError_POH_TIMEOUT
#define _bam_types_SchedulingError_MAX bam_types_SchedulingError_CONTAINER_FULL
#define _bam_types_SchedulingError_ARRAYSIZE ((bam_types_SchedulingError)(bam_types_SchedulingError_CONTAINER_FULL+1))

#define _bam_types_TransactionErrorReason_MIN bam_types_TransactionErrorReason_ACCOUNT_IN_USE
#define _bam_types_TransactionErrorReason_MAX bam_types_TransactionErrorReason_COMMIT_CANCELLED
#define _bam_types_TransactionErrorReason_ARRAYSIZE ((bam_types_TransactionErrorReason)(bam_types_TransactionErrorReason_COMMIT_CANCELLED+1))
















#define bam_types_NotCommitted_reason_scheduling_error_ENUMTYPE bam_types_SchedulingError

#define bam_types_DeserializationError_reason_ENUMTYPE bam_types_DeserializationErrorReason



#define bam_types_TransactionError_reason_ENUMTYPE bam_types_TransactionErrorReason





/* Initializer values for message structs */
#define bam_types_AuthProof_init_default         {"", "", ""}
#define bam_types_BuilderHeartBeat_init_default  {0}
#define bam_types_ValidatorHeartBeat_init_default {0}
#define bam_types_Ping_init_default              {0}
#define bam_types_Pong_init_default              {0}
#define bam_types_Socket_init_default            {"", 0}
#define bam_types_LeaderState_init_default       {0, 0, 0}
#define bam_types_AtomicTxnBatch_init_default    {0, 0, {{NULL}, NULL}}
#define bam_types_MultipleAtomicTxnBatch_init_default {{{NULL}, NULL}}
#define bam_types_AtomicTxnBatchResult_init_default {0, 0, {bam_types_Committed_init_default}}
#define bam_types_MultipleAtomicTxnBatchResult_init_default {{{NULL}, NULL}}
#define bam_types_Packet_init_default            {{0, {0}}, false, bam_types_Meta_init_default}
#define bam_types_Meta_init_default              {0, false, bam_types_PacketFlags_init_default}
#define bam_types_PacketFlags_init_default       {0, 0}
#define bam_types_Committed_init_default         {{{NULL}, NULL}}
#define bam_types_NotCommitted_init_default      {0, {bam_types_TransactionError_init_default}}
#define bam_types_DeserializationError_init_default {0, _bam_types_DeserializationErrorReason_MIN}
#define bam_types_GenericInvalid_init_default    {""}
#define bam_types_PohTimeout_init_default        {0}
#define bam_types_TransactionError_init_default  {0, _bam_types_TransactionErrorReason_MIN}
#define bam_types_TransactionCommittedResult_init_default {0, 0, 0, 0}
#define bam_types_BlockEngineBuilderConfig_init_default {"", 0}
#define bam_types_BamConfig_init_default         {"", 0, false, bam_types_Socket_init_default, false, bam_types_Socket_init_default, 0, {bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default, bam_types_Socket_init_default}}
#define bam_types_AuthProof_init_zero            {"", "", ""}
#define bam_types_BuilderHeartBeat_init_zero     {0}
#define bam_types_ValidatorHeartBeat_init_zero   {0}
#define bam_types_Ping_init_zero                 {0}
#define bam_types_Pong_init_zero                 {0}
#define bam_types_Socket_init_zero               {"", 0}
#define bam_types_LeaderState_init_zero          {0, 0, 0}
#define bam_types_AtomicTxnBatch_init_zero       {0, 0, {{NULL}, NULL}}
#define bam_types_MultipleAtomicTxnBatch_init_zero {{{NULL}, NULL}}
#define bam_types_AtomicTxnBatchResult_init_zero {0, 0, {bam_types_Committed_init_zero}}
#define bam_types_MultipleAtomicTxnBatchResult_init_zero {{{NULL}, NULL}}
#define bam_types_Packet_init_zero               {{0, {0}}, false, bam_types_Meta_init_zero}
#define bam_types_Meta_init_zero                 {0, false, bam_types_PacketFlags_init_zero}
#define bam_types_PacketFlags_init_zero          {0, 0}
#define bam_types_Committed_init_zero            {{{NULL}, NULL}}
#define bam_types_NotCommitted_init_zero         {0, {bam_types_TransactionError_init_zero}}
#define bam_types_DeserializationError_init_zero {0, _bam_types_DeserializationErrorReason_MIN}
#define bam_types_GenericInvalid_init_zero       {""}
#define bam_types_PohTimeout_init_zero           {0}
#define bam_types_TransactionError_init_zero     {0, _bam_types_TransactionErrorReason_MIN}
#define bam_types_TransactionCommittedResult_init_zero {0, 0, 0, 0}
#define bam_types_BlockEngineBuilderConfig_init_zero {"", 0}
#define bam_types_BamConfig_init_zero            {"", 0, false, bam_types_Socket_init_zero, false, bam_types_Socket_init_zero, 0, {bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero, bam_types_Socket_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define bam_types_AuthProof_challenge_to_sign_tag 1
#define bam_types_AuthProof_validator_pubkey_tag 2
#define bam_types_AuthProof_signature_tag        3
#define bam_types_BuilderHeartBeat_time_sent_microseconds_tag 1
#define bam_types_ValidatorHeartBeat_time_sent_microseconds_tag 1
#define bam_types_Ping_id_tag                    1
#define bam_types_Pong_id_tag                    1
#define bam_types_Socket_ip_tag                  1
#define bam_types_Socket_port_tag                2
#define bam_types_LeaderState_slot_tag           1
#define bam_types_LeaderState_tick_tag           2
#define bam_types_LeaderState_slot_cu_budget_remaining_tag 3
#define bam_types_AtomicTxnBatch_seq_id_tag      1
#define bam_types_AtomicTxnBatch_max_schedule_slot_tag 2
#define bam_types_AtomicTxnBatch_packets_tag     3
#define bam_types_MultipleAtomicTxnBatch_batches_tag 3
#define bam_types_MultipleAtomicTxnBatchResult_results_tag 1
#define bam_types_PacketFlags_simple_vote_tx_tag 1
#define bam_types_PacketFlags_revert_on_error_tag 2
#define bam_types_Meta_size_tag                  1
#define bam_types_Meta_flags_tag                 2
#define bam_types_Packet_data_tag                1
#define bam_types_Packet_meta_tag                2
#define bam_types_Committed_transaction_results_tag 1
#define bam_types_DeserializationError_index_tag 1
#define bam_types_DeserializationError_reason_tag 2
#define bam_types_GenericInvalid_message_tag     1
#define bam_types_TransactionError_index_tag     1
#define bam_types_TransactionError_reason_tag    2
#define bam_types_NotCommitted_transaction_error_tag 1
#define bam_types_NotCommitted_scheduling_error_tag 2
#define bam_types_NotCommitted_generic_invalid_tag 3
#define bam_types_NotCommitted_deserialization_error_tag 4
#define bam_types_AtomicTxnBatchResult_seq_id_tag 1
#define bam_types_AtomicTxnBatchResult_committed_tag 2
#define bam_types_AtomicTxnBatchResult_not_committed_tag 3
#define bam_types_TransactionCommittedResult_cus_consumed_tag 1
#define bam_types_TransactionCommittedResult_feepayer_balance_lamports_tag 2
#define bam_types_TransactionCommittedResult_loaded_accounts_data_size_tag 3
#define bam_types_TransactionCommittedResult_execution_success_tag 4
#define bam_types_BlockEngineBuilderConfig_builder_pubkey_tag 1
#define bam_types_BlockEngineBuilderConfig_builder_commission_tag 2
#define bam_types_BamConfig_prio_fee_recipient_pubkey_tag 1
#define bam_types_BamConfig_commission_bps_tag   2
#define bam_types_BamConfig_tpu_sock_tag         3
#define bam_types_BamConfig_tpu_fwd_sock_tag     4
#define bam_types_BamConfig_shred_socks_tag      5

/* Struct field encoding specification for nanopb */
#define bam_types_AuthProof_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   challenge_to_sign,   1) \
X(a, STATIC,   SINGULAR, STRING,   validator_pubkey,   2) \
X(a, STATIC,   SINGULAR, STRING,   signature,         3)
#define bam_types_AuthProof_CALLBACK NULL
#define bam_types_AuthProof_DEFAULT NULL

#define bam_types_BuilderHeartBeat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   time_sent_microseconds,   1)
#define bam_types_BuilderHeartBeat_CALLBACK NULL
#define bam_types_BuilderHeartBeat_DEFAULT NULL

#define bam_types_ValidatorHeartBeat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   time_sent_microseconds,   1)
#define bam_types_ValidatorHeartBeat_CALLBACK NULL
#define bam_types_ValidatorHeartBeat_DEFAULT NULL

#define bam_types_Ping_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define bam_types_Ping_CALLBACK NULL
#define bam_types_Ping_DEFAULT NULL

#define bam_types_Pong_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define bam_types_Pong_CALLBACK NULL
#define bam_types_Pong_DEFAULT NULL

#define bam_types_Socket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   ip,                1) \
X(a, STATIC,   SINGULAR, UINT32,   port,              2)
#define bam_types_Socket_CALLBACK NULL
#define bam_types_Socket_DEFAULT NULL

#define bam_types_LeaderState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              1) \
X(a, STATIC,   SINGULAR, UINT32,   tick,              2) \
X(a, STATIC,   SINGULAR, UINT32,   slot_cu_budget_remaining,   3)
#define bam_types_LeaderState_CALLBACK NULL
#define bam_types_LeaderState_DEFAULT NULL

#define bam_types_AtomicTxnBatch_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq_id,            1) \
X(a, STATIC,   SINGULAR, UINT64,   max_schedule_slot,   2) \
X(a, CALLBACK, REPEATED, MESSAGE,  packets,           3)
#define bam_types_AtomicTxnBatch_CALLBACK pb_default_field_callback
#define bam_types_AtomicTxnBatch_DEFAULT NULL
#define bam_types_AtomicTxnBatch_packets_MSGTYPE bam_types_Packet

#define bam_types_MultipleAtomicTxnBatch_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  batches,           3)
#define bam_types_MultipleAtomicTxnBatch_CALLBACK pb_default_field_callback
#define bam_types_MultipleAtomicTxnBatch_DEFAULT NULL
#define bam_types_MultipleAtomicTxnBatch_batches_MSGTYPE bam_types_AtomicTxnBatch

#define bam_types_AtomicTxnBatchResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq_id,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,committed,result.committed),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,not_committed,result.not_committed),   3)
#define bam_types_AtomicTxnBatchResult_CALLBACK NULL
#define bam_types_AtomicTxnBatchResult_DEFAULT NULL
#define bam_types_AtomicTxnBatchResult_result_committed_MSGTYPE bam_types_Committed
#define bam_types_AtomicTxnBatchResult_result_not_committed_MSGTYPE bam_types_NotCommitted

#define bam_types_MultipleAtomicTxnBatchResult_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  results,           1)
#define bam_types_MultipleAtomicTxnBatchResult_CALLBACK pb_default_field_callback
#define bam_types_MultipleAtomicTxnBatchResult_DEFAULT NULL
#define bam_types_MultipleAtomicTxnBatchResult_results_MSGTYPE bam_types_AtomicTxnBatchResult

#define bam_types_Packet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  meta,              2)
#define bam_types_Packet_CALLBACK NULL
#define bam_types_Packet_DEFAULT NULL
#define bam_types_Packet_meta_MSGTYPE bam_types_Meta

#define bam_types_Meta_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   size,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  flags,             2)
#define bam_types_Meta_CALLBACK NULL
#define bam_types_Meta_DEFAULT NULL
#define bam_types_Meta_flags_MSGTYPE bam_types_PacketFlags

#define bam_types_PacketFlags_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     simple_vote_tx,    1) \
X(a, STATIC,   SINGULAR, BOOL,     revert_on_error,   2)
#define bam_types_PacketFlags_CALLBACK NULL
#define bam_types_PacketFlags_DEFAULT NULL

#define bam_types_Committed_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  transaction_results,   1)
#define bam_types_Committed_CALLBACK pb_default_field_callback
#define bam_types_Committed_DEFAULT NULL
#define bam_types_Committed_transaction_results_MSGTYPE bam_types_TransactionCommittedResult

#define bam_types_NotCommitted_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (reason,transaction_error,reason.transaction_error),   1) \
X(a, STATIC,   ONEOF,    UENUM,    (reason,scheduling_error,reason.scheduling_error),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (reason,generic_invalid,reason.generic_invalid),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (reason,deserialization_error,reason.deserialization_error),   4)
#define bam_types_NotCommitted_CALLBACK NULL
#define bam_types_NotCommitted_DEFAULT NULL
#define bam_types_NotCommitted_reason_transaction_error_MSGTYPE bam_types_TransactionError
#define bam_types_NotCommitted_reason_generic_invalid_MSGTYPE bam_types_GenericInvalid
#define bam_types_NotCommitted_reason_deserialization_error_MSGTYPE bam_types_DeserializationError

#define bam_types_DeserializationError_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            2)
#define bam_types_DeserializationError_CALLBACK NULL
#define bam_types_DeserializationError_DEFAULT NULL

#define bam_types_GenericInvalid_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1)
#define bam_types_GenericInvalid_CALLBACK NULL
#define bam_types_GenericInvalid_DEFAULT NULL

#define bam_types_PohTimeout_FIELDLIST(X, a) \

#define bam_types_PohTimeout_CALLBACK NULL
#define bam_types_PohTimeout_DEFAULT NULL

#define bam_types_TransactionError_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            2)
#define bam_types_TransactionError_CALLBACK NULL
#define bam_types_TransactionError_DEFAULT NULL

#define bam_types_TransactionCommittedResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   cus_consumed,      1) \
X(a, STATIC,   SINGULAR, UINT64,   feepayer_balance_lamports,   2) \
X(a, STATIC,   SINGULAR, UINT32,   loaded_accounts_data_size,   3) \
X(a, STATIC,   SINGULAR, BOOL,     execution_success,   4)
#define bam_types_TransactionCommittedResult_CALLBACK NULL
#define bam_types_TransactionCommittedResult_DEFAULT NULL

#define bam_types_BlockEngineBuilderConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   builder_pubkey,    1) \
X(a, STATIC,   SINGULAR, UINT32,   builder_commission,   2)
#define bam_types_BlockEngineBuilderConfig_CALLBACK NULL
#define bam_types_BlockEngineBuilderConfig_DEFAULT NULL

#define bam_types_BamConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   prio_fee_recipient_pubkey,   1) \
X(a, STATIC,   SINGULAR, UINT32,   commission_bps,    2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tpu_sock,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tpu_fwd_sock,      4) \
X(a, STATIC,   REPEATED, MESSAGE,  shred_socks,       5)
#define bam_types_BamConfig_CALLBACK NULL
#define bam_types_BamConfig_DEFAULT NULL
#define bam_types_BamConfig_tpu_sock_MSGTYPE bam_types_Socket
#define bam_types_BamConfig_tpu_fwd_sock_MSGTYPE bam_types_Socket
#define bam_types_BamConfig_shred_socks_MSGTYPE bam_types_Socket

extern const pb_msgdesc_t bam_types_AuthProof_msg;
extern const pb_msgdesc_t bam_types_BuilderHeartBeat_msg;
extern const pb_msgdesc_t bam_types_ValidatorHeartBeat_msg;
extern const pb_msgdesc_t bam_types_Ping_msg;
extern const pb_msgdesc_t bam_types_Pong_msg;
extern const pb_msgdesc_t bam_types_Socket_msg;
extern const pb_msgdesc_t bam_types_LeaderState_msg;
extern const pb_msgdesc_t bam_types_AtomicTxnBatch_msg;
extern const pb_msgdesc_t bam_types_MultipleAtomicTxnBatch_msg;
extern const pb_msgdesc_t bam_types_AtomicTxnBatchResult_msg;
extern const pb_msgdesc_t bam_types_MultipleAtomicTxnBatchResult_msg;
extern const pb_msgdesc_t bam_types_Packet_msg;
extern const pb_msgdesc_t bam_types_Meta_msg;
extern const pb_msgdesc_t bam_types_PacketFlags_msg;
extern const pb_msgdesc_t bam_types_Committed_msg;
extern const pb_msgdesc_t bam_types_NotCommitted_msg;
extern const pb_msgdesc_t bam_types_DeserializationError_msg;
extern const pb_msgdesc_t bam_types_GenericInvalid_msg;
extern const pb_msgdesc_t bam_types_PohTimeout_msg;
extern const pb_msgdesc_t bam_types_TransactionError_msg;
extern const pb_msgdesc_t bam_types_TransactionCommittedResult_msg;
extern const pb_msgdesc_t bam_types_BlockEngineBuilderConfig_msg;
extern const pb_msgdesc_t bam_types_BamConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define bam_types_AuthProof_fields &bam_types_AuthProof_msg
#define bam_types_BuilderHeartBeat_fields &bam_types_BuilderHeartBeat_msg
#define bam_types_ValidatorHeartBeat_fields &bam_types_ValidatorHeartBeat_msg
#define bam_types_Ping_fields &bam_types_Ping_msg
#define bam_types_Pong_fields &bam_types_Pong_msg
#define bam_types_Socket_fields &bam_types_Socket_msg
#define bam_types_LeaderState_fields &bam_types_LeaderState_msg
#define bam_types_AtomicTxnBatch_fields &bam_types_AtomicTxnBatch_msg
#define bam_types_MultipleAtomicTxnBatch_fields &bam_types_MultipleAtomicTxnBatch_msg
#define bam_types_AtomicTxnBatchResult_fields &bam_types_AtomicTxnBatchResult_msg
#define bam_types_MultipleAtomicTxnBatchResult_fields &bam_types_MultipleAtomicTxnBatchResult_msg
#define bam_types_Packet_fields &bam_types_Packet_msg
#define bam_types_Meta_fields &bam_types_Meta_msg
#define bam_types_PacketFlags_fields &bam_types_PacketFlags_msg
#define bam_types_Committed_fields &bam_types_Committed_msg
#define bam_types_NotCommitted_fields &bam_types_NotCommitted_msg
#define bam_types_DeserializationError_fields &bam_types_DeserializationError_msg
#define bam_types_GenericInvalid_fields &bam_types_GenericInvalid_msg
#define bam_types_PohTimeout_fields &bam_types_PohTimeout_msg
#define bam_types_TransactionError_fields &bam_types_TransactionError_msg
#define bam_types_TransactionCommittedResult_fields &bam_types_TransactionCommittedResult_msg
#define bam_types_BlockEngineBuilderConfig_fields &bam_types_BlockEngineBuilderConfig_msg
#define bam_types_BamConfig_fields &bam_types_BamConfig_msg

/* Maximum encoded size of messages (where known) */
/* bam_types_AtomicTxnBatch_size depends on runtime parameters */
/* bam_types_MultipleAtomicTxnBatch_size depends on runtime parameters */
/* bam_types_AtomicTxnBatchResult_size depends on runtime parameters */
/* bam_types_MultipleAtomicTxnBatchResult_size depends on runtime parameters */
/* bam_types_Committed_size depends on runtime parameters */
#define BAM_TYPES_BAM_TYPES_PB_H_MAX_SIZE        bam_types_Packet_size
#define bam_types_AuthProof_size                 325
#define bam_types_BamConfig_size                 2553
#define bam_types_BlockEngineBuilderConfig_size  71
#define bam_types_BuilderHeartBeat_size          11
#define bam_types_DeserializationError_size      8
#define bam_types_GenericInvalid_size            258
#define bam_types_LeaderState_size               23
#define bam_types_Meta_size                      17
#define bam_types_NotCommitted_size              261
#define bam_types_PacketFlags_size               4
#define bam_types_Packet_size                    4118
#define bam_types_Ping_size                      6
#define bam_types_PohTimeout_size                0
#define bam_types_Pong_size                      6
#define bam_types_Socket_size                    71
#define bam_types_TransactionCommittedResult_size 25
#define bam_types_TransactionError_size          8
#define bam_types_ValidatorHeartBeat_size        11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
