/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "bam_api.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(bam_api_AuthChallengeRequest, bam_api_AuthChallengeRequest, AUTO)


PB_BIND(bam_api_AuthChallengeResponse, bam_api_AuthChallengeResponse, AUTO)


PB_BIND(bam_api_ConfigRequest, bam_api_ConfigRequest, AUTO)


PB_BIND(bam_api_ConfigResponse, bam_api_ConfigResponse, AUTO)


PB_BIND(bam_api_SchedulerMessage, bam_api_SchedulerMessage, AUTO)


PB_BIND(bam_api_SchedulerMessageV0, bam_api_SchedulerMessageV0, AUTO)


PB_BIND(bam_api_SchedulerResponse, bam_api_SchedulerResponse, AUTO)


PB_BIND(bam_api_SchedulerResponseV0, bam_api_SchedulerResponseV0, AUTO)



