/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_BAM_API_BAM_API_PB_H_INCLUDED
#define PB_BAM_API_BAM_API_PB_H_INCLUDED
#include "../../../third_party/nanopb/pb_firedancer.h"
#include "bam_types.pb.h"
#include "google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Request to get an authentication challenge to sign */
typedef struct _bam_api_AuthChallengeRequest {
    char dummy_field;
} bam_api_AuthChallengeRequest;

/* Response containing the challenge to sign */
typedef struct _bam_api_AuthChallengeResponse {
    char challenge_to_sign[128];
} bam_api_AuthChallengeResponse;

/* Request to get the block-engine + BAM node configuration */
typedef struct _bam_api_ConfigRequest {
    char dummy_field;
} bam_api_ConfigRequest;

typedef struct _bam_api_ConfigResponse {
    bool has_block_engine_config;
    bam_types_BlockEngineBuilderConfig block_engine_config;
    bool has_bam_config;
    bam_types_BamConfig bam_config;
} bam_api_ConfigResponse;

typedef struct _bam_api_SchedulerMessageV0 {
    pb_size_t which_msg;
    union {
        bam_types_ValidatorHeartBeat heart_beat;
        bam_types_LeaderState leader_state;
        bam_types_MultipleAtomicTxnBatchResult multiple_atomic_txn_batch_result;
        bam_types_AuthProof auth_proof;
        bam_types_Pong pong;
    } msg;
} bam_api_SchedulerMessageV0;

/* Message sent by the Validator to the Node */
typedef struct _bam_api_SchedulerMessage {
    pb_size_t which_versioned_msg;
    union {
        bam_api_SchedulerMessageV0 v0;
    } versioned_msg;
} bam_api_SchedulerMessage;

typedef struct _bam_api_SchedulerResponseV0 {
    pb_size_t which_resp;
    union {
        bam_types_BuilderHeartBeat heart_beat;
        bam_types_MultipleAtomicTxnBatch multiple_atomic_txn_batch;
        bam_types_Ping ping;
    } resp;
} bam_api_SchedulerResponseV0;

/* Response sent by the Node to the Validator */
typedef struct _bam_api_SchedulerResponse {
    pb_size_t which_versioned_msg;
    union {
        bam_api_SchedulerResponseV0 v0;
    } versioned_msg;
} bam_api_SchedulerResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define bam_api_AuthChallengeRequest_init_default {0}
#define bam_api_AuthChallengeResponse_init_default {""}
#define bam_api_ConfigRequest_init_default       {0}
#define bam_api_ConfigResponse_init_default      {false, bam_types_BlockEngineBuilderConfig_init_default, false, bam_types_BamConfig_init_default}
#define bam_api_SchedulerMessage_init_default    {0, {bam_api_SchedulerMessageV0_init_default}}
#define bam_api_SchedulerMessageV0_init_default  {0, {bam_types_ValidatorHeartBeat_init_default}}
#define bam_api_SchedulerResponse_init_default   {0, {bam_api_SchedulerResponseV0_init_default}}
#define bam_api_SchedulerResponseV0_init_default {0, {bam_types_BuilderHeartBeat_init_default}}
#define bam_api_AuthChallengeRequest_init_zero   {0}
#define bam_api_AuthChallengeResponse_init_zero  {""}
#define bam_api_ConfigRequest_init_zero          {0}
#define bam_api_ConfigResponse_init_zero         {false, bam_types_BlockEngineBuilderConfig_init_zero, false, bam_types_BamConfig_init_zero}
#define bam_api_SchedulerMessage_init_zero       {0, {bam_api_SchedulerMessageV0_init_zero}}
#define bam_api_SchedulerMessageV0_init_zero     {0, {bam_types_ValidatorHeartBeat_init_zero}}
#define bam_api_SchedulerResponse_init_zero      {0, {bam_api_SchedulerResponseV0_init_zero}}
#define bam_api_SchedulerResponseV0_init_zero    {0, {bam_types_BuilderHeartBeat_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define bam_api_AuthChallengeResponse_challenge_to_sign_tag 1
#define bam_api_ConfigResponse_block_engine_config_tag 1
#define bam_api_ConfigResponse_bam_config_tag    2
#define bam_api_SchedulerMessageV0_heart_beat_tag 1
#define bam_api_SchedulerMessageV0_leader_state_tag 2
#define bam_api_SchedulerMessageV0_multiple_atomic_txn_batch_result_tag 3
#define bam_api_SchedulerMessageV0_auth_proof_tag 4
#define bam_api_SchedulerMessageV0_pong_tag    5
#define bam_api_SchedulerMessage_v0_tag          1
#define bam_api_SchedulerResponseV0_heart_beat_tag 1
#define bam_api_SchedulerResponseV0_multiple_atomic_txn_batch_tag 2
#define bam_api_SchedulerResponseV0_ping_tag    3
#define bam_api_SchedulerResponse_v0_tag         1

/* Struct field encoding specification for nanopb */
#define bam_api_AuthChallengeRequest_FIELDLIST(X, a) \

#define bam_api_AuthChallengeRequest_CALLBACK NULL
#define bam_api_AuthChallengeRequest_DEFAULT NULL

#define bam_api_AuthChallengeResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   challenge_to_sign,   1)
#define bam_api_AuthChallengeResponse_CALLBACK NULL
#define bam_api_AuthChallengeResponse_DEFAULT NULL

#define bam_api_ConfigRequest_FIELDLIST(X, a) \

#define bam_api_ConfigRequest_CALLBACK NULL
#define bam_api_ConfigRequest_DEFAULT NULL

#define bam_api_ConfigResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  block_engine_config,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bam_config,        2)
#define bam_api_ConfigResponse_CALLBACK NULL
#define bam_api_ConfigResponse_DEFAULT NULL
#define bam_api_ConfigResponse_block_engine_config_MSGTYPE bam_types_BlockEngineBuilderConfig
#define bam_api_ConfigResponse_bam_config_MSGTYPE bam_types_BamConfig

#define bam_api_SchedulerMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (versioned_msg,v0,versioned_msg.v0),   1)
#define bam_api_SchedulerMessage_CALLBACK NULL
#define bam_api_SchedulerMessage_DEFAULT NULL
#define bam_api_SchedulerMessage_versioned_msg_v0_MSGTYPE bam_api_SchedulerMessageV0

#define bam_api_SchedulerMessageV0_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,heart_beat,msg.heart_beat),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,leader_state,msg.leader_state),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,multiple_atomic_txn_batch_result,msg.multiple_atomic_txn_batch_result),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,auth_proof,msg.auth_proof),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,pong,msg.pong),   5)
#define bam_api_SchedulerMessageV0_CALLBACK NULL
#define bam_api_SchedulerMessageV0_DEFAULT NULL
#define bam_api_SchedulerMessageV0_msg_heart_beat_MSGTYPE bam_types_ValidatorHeartBeat
#define bam_api_SchedulerMessageV0_msg_leader_state_MSGTYPE bam_types_LeaderState
#define bam_api_SchedulerMessageV0_msg_multiple_atomic_txn_batch_result_MSGTYPE bam_types_MultipleAtomicTxnBatchResult
#define bam_api_SchedulerMessageV0_msg_auth_proof_MSGTYPE bam_types_AuthProof
#define bam_api_SchedulerMessageV0_msg_pong_MSGTYPE bam_types_Pong

#define bam_api_SchedulerResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (versioned_msg,v0,versioned_msg.v0),   1)
#define bam_api_SchedulerResponse_CALLBACK NULL
#define bam_api_SchedulerResponse_DEFAULT NULL
#define bam_api_SchedulerResponse_versioned_msg_v0_MSGTYPE bam_api_SchedulerResponseV0

#define bam_api_SchedulerResponseV0_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (resp,heart_beat,resp.heart_beat),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (resp,multiple_atomic_txn_batch,resp.multiple_atomic_txn_batch),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (resp,ping,resp.ping),   3)
#define bam_api_SchedulerResponseV0_CALLBACK NULL
#define bam_api_SchedulerResponseV0_DEFAULT NULL
#define bam_api_SchedulerResponseV0_resp_heart_beat_MSGTYPE bam_types_BuilderHeartBeat
#define bam_api_SchedulerResponseV0_resp_multiple_atomic_txn_batch_MSGTYPE bam_types_MultipleAtomicTxnBatch
#define bam_api_SchedulerResponseV0_resp_ping_MSGTYPE bam_types_Ping

extern const pb_msgdesc_t bam_api_AuthChallengeRequest_msg;
extern const pb_msgdesc_t bam_api_AuthChallengeResponse_msg;
extern const pb_msgdesc_t bam_api_ConfigRequest_msg;
extern const pb_msgdesc_t bam_api_ConfigResponse_msg;
extern const pb_msgdesc_t bam_api_SchedulerMessage_msg;
extern const pb_msgdesc_t bam_api_SchedulerMessageV0_msg;
extern const pb_msgdesc_t bam_api_SchedulerResponse_msg;
extern const pb_msgdesc_t bam_api_SchedulerResponseV0_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define bam_api_AuthChallengeRequest_fields &bam_api_AuthChallengeRequest_msg
#define bam_api_AuthChallengeResponse_fields &bam_api_AuthChallengeResponse_msg
#define bam_api_ConfigRequest_fields &bam_api_ConfigRequest_msg
#define bam_api_ConfigResponse_fields &bam_api_ConfigResponse_msg
#define bam_api_SchedulerMessage_fields &bam_api_SchedulerMessage_msg
#define bam_api_SchedulerMessageV0_fields &bam_api_SchedulerMessageV0_msg
#define bam_api_SchedulerResponse_fields &bam_api_SchedulerResponse_msg
#define bam_api_SchedulerResponseV0_fields &bam_api_SchedulerResponseV0_msg

/* Maximum encoded size of messages (where known) */
#if defined(bam_types_MultipleAtomicTxnBatchResult_size) && defined(bam_types_AuthProof_size) && defined(bam_types_Pong_size)
union bam_api_SchedulerMessageV0_msg_size_union {char f3[(6 + bam_types_MultipleAtomicTxnBatchResult_size)]; char f4[(6 + bam_types_AuthProof_size)]; char f5[(6 + bam_types_Pong_size)]; char f0[25];};
#endif
#if defined(bam_types_MultipleAtomicTxnBatchResult_size) && defined(bam_types_AuthProof_size) && defined(bam_types_Pong_size)
union bam_api_SchedulerMessageV0_msg_size_union {char f3[(6 + bam_types_MultipleAtomicTxnBatchResult_size)]; char f4[(6 + bam_types_AuthProof_size)]; char f5[(6 + bam_types_Pong_size)]; char f0[25];};
#endif
#if defined(bam_types_MultipleAtomicTxnBatch_size) && defined(bam_types_Ping_size)
union bam_api_SchedulerResponseV0_resp_size_union {char f2[(6 + bam_types_MultipleAtomicTxnBatch_size)]; char f3[(6 + bam_types_Ping_size)]; char f0[13];};
#endif
#if defined(bam_types_MultipleAtomicTxnBatch_size) && defined(bam_types_Ping_size)
union bam_api_SchedulerResponseV0_resp_size_union {char f2[(6 + bam_types_MultipleAtomicTxnBatch_size)]; char f3[(6 + bam_types_Ping_size)]; char f0[13];};
#endif
#define BAM_API_BAM_API_PB_H_MAX_SIZE            bam_api_AuthChallengeResponse_size
#define bam_api_AuthChallengeRequest_size        0
#define bam_api_AuthChallengeResponse_size       130
#define bam_api_ConfigRequest_size               0
#if defined(bam_types_BlockEngineBuilderConfig_size) && defined(bam_types_BamConfig_size)
#define bam_api_ConfigResponse_size              (12 + bam_types_BlockEngineBuilderConfig_size + bam_types_BamConfig_size)
#endif
#if defined(bam_types_MultipleAtomicTxnBatchResult_size) && defined(bam_types_AuthProof_size) && defined(bam_types_Pong_size)
#define bam_api_SchedulerMessageV0_size          (0 + sizeof(union bam_api_SchedulerMessageV0_msg_size_union))
#define bam_api_SchedulerMessage_size            (6 + sizeof(union bam_api_SchedulerMessageV0_msg_size_union))
#endif
#if defined(bam_types_MultipleAtomicTxnBatch_size) && defined(bam_types_Ping_size)
#define bam_api_SchedulerResponseV0_size         (0 + sizeof(union bam_api_SchedulerResponseV0_resp_size_union))
#define bam_api_SchedulerResponse_size           (6 + sizeof(union bam_api_SchedulerResponseV0_resp_size_union))
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
